### ISSUE TITLE
Documentation for sequencing types

### ISSUE THREAD

**Issue by aswistak-stjude** [stjude/sjcloud-docs#48]
I modified the badge tooltips on the databrowser (the black popup that occurs when a user mouse overs the `WSG`, `WES`, `BAM`, etc buttons in the table) so the tooltips have clickable links. For now, [only file type badges have links](https://github.com/stjude/sjcloud-platform/commit/d542f957ea14274abac3a064421adaa206182f3e#diff-380fb5980e0e5ea0ff21527b68f79e60) because we only have documentation on file types. It would be useful to have helpful documentation for sequencing types as well.

<img width="236" alt="Screen Shot 2019-03-13 at 1 10 30 PM" src="https://user-images.githubusercontent.com/48030057/54303679-87a7b400-4591-11e9-8326-6d065cf562d3.png">

**Comment by mtreadwa** [comment]
Clay, is there any sj cloud specific information on sequence types worth including in the documentation? If we'd prefer to tooltips to have links we could just link to wikipedia for sequence types.

**Comment by adthrasher** [comment]
@claymcleod - If you want, I can help draft text for the sequencing types.

**Comment by claymcleod** [comment]
We have some data here already: https://www.stjude.cloud/docs/guides/data/types-of-data/. We should probably link to those headings (for instance, with `BAM`, just link to the overarching header, not the WGS/WXS/RNA-Seq specific headings).

@adthrasher, yes, I would really appreciate that. With anything that is lacking, would you mind taking a look and updating the information? Up until this point, we have taken a "lazy evaluation" approach to these sections :).

**Comment by adthrasher** [comment]
I would link to the guide for the data types from within the tooltips (for WGS, WES, and RNA-Seq) on the data page. The description of how each data type was generated is probably more useful to a user than a description of the sequencing methods. 

One issue with doing that is we have "WES" as the abbreviation for whole-exome on the data page and we use "WXS" in the documentation.

**Comment by mtreadwa** [comment]
I agree with Andrew on the first point. 
And the data browser and other parts of the documentation use "WES", so I think we should go with that one. I'm working on documentation today, so I'll go ahead a change the data types page to agree.
