### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by aswistak-stjude** [stjude/sjcloud-docs#65]
I merged a pull request on platform to update documentation links to URLs that had previously worked.

The URL the previously worked 
```https://stjude.cloud/docs/guides/glossary/data-access-unit/#childhood-cancer-survivor-study-ccss```
now should be 
```https://stjude.cloud/docs/glossary/#childhood-cancer-survivor-study-ccss```.

Platform is updated again, but for future changes, is there a way we can make old links redirect to new locations so every site that links to documentation doesn't immediately have broken links?

**Comment by claymcleod** [comment]
Is this the right approach, or should it be part of Arthur's constant scanning? My concern would be that we are left with a web of redirects. I do admit, it was bad timing in this particular instance

**Comment by aswistak-stjude** [comment]
Ideally we go through some sort of deprecation cycle to give us time to update relevant platforms/portals/sites/etc and then remove the redirect.

**Comment by mtreadwa** [comment]
Closing because Arthur now checks for broken links regularly.

**Comment by ajswis** [comment]
This has occurred again. Links on the data browser were leading to 404 pages, but has recently been fixed (https://github.com/stjude/sjcloud-platform/pull/161). Affected links were updated here on commit https://github.com/stjudecloud/docs/commit/38ae319628d7187114bf049ae02923e3482ff324.

I think this question is still relevant:
> [...] is there a way we can make old links redirect to new locations so every site that links to documentation doesn't immediately have broken links?
